In [22]:
from mido import MidiFile
import os,sys
import re
import numpy as np
#import tensorflow as tf
import csv
import keras
from keras.layers import Dense, Flatten, Dropout
from keras.layers import Conv2D, MaxPooling2D
from keras.models import Sequential
import matplotlib.pylab as plt
from __future__ import print_function
from keras.models import model_from_json 
#SURAJ PATH
pth = "D:\study\major project\scl\src"
os.chdir(pth)


In [5]:
# elec_gt 0
# percussive 1
# voi_ensem 2
# saxphone 3
# synth_lead 4
# keyboard 5
# brass 6
# strings 7
# str_ensem 8
# fx 9
# woodwind 10
# c_percus 11
# pipe 12
# ethnic 13
# synth_pad 14
# other 15
# acou_gt 16
# organ 17
# electric 18
# bass 19

instruments = [0]*128 
instruments[0]=5
instruments[1]=5
instruments[2]=5
instruments[3]=5
instruments[4]=5
instruments[5]=18
instruments[6]=18
instruments[7]=15
instruments[8]=15
instruments[9]=11
instruments[10]=11
instruments[11]=11
instruments[12]=11
instruments[13]=11
instruments[14]=11
instruments[15]=11
instruments[16]=11
instruments[17]=18
instruments[18]=17
instruments[19]=18
instruments[20]=17
instruments[21]=17
instruments[22]=17
instruments[23]=17
instruments[24]=17
instruments[25]=16
instruments[26]=16
instruments[27]=0
instruments[28]=0
instruments[29]=0
instruments[30]=0
instruments[31]=0
instruments[32]=0
instruments[33]=19
instruments[34]=19
instruments[35]=19
instruments[36]=19
instruments[37]=19
instruments[38]=19
instruments[39]=19
instruments[40]=19
instruments[41]=7
instruments[42]=7
instruments[43]=7
instruments[44]=7
instruments[45]=7
instruments[46]=7
instruments[47]=7
instruments[48]=7
instruments[49]=8
instruments[50]=8
instruments[51]=8
instruments[52]=8
instruments[53]=2
instruments[54]=2
instruments[55]=2
instruments[56]=2
instruments[57]=6
instruments[58]=6
instruments[59]=6
instruments[60]=6
instruments[61]=6
instruments[62]=6
instruments[63]=6
instruments[64]=6
instruments[65]=3
instruments[66]=3
instruments[67]=3
instruments[68]=3
instruments[69]=10
instruments[70]=10
instruments[71]=10
instruments[72]=10
instruments[73]=10
instruments[74]=10
instruments[75]=10
instruments[76]=10
instruments[77]=12
instruments[78]=12
instruments[79]=12
instruments[80]=12
instruments[81]=4
instruments[82]=4
instruments[83]=4
instruments[84]=4
instruments[85]=4
instruments[86]=4
instruments[87]=4
instruments[88]=4
instruments[89]=14
instruments[90]=14
instruments[91]=14
instruments[92]=14
instruments[93]=14
instruments[94]=14
instruments[95]=14
instruments[96]=14
instruments[97]=9
instruments[98]=9
instruments[99]=9
instruments[100]=9
instruments[101]=9
instruments[102]=9
instruments[103]=9
instruments[104]=9
instruments[105]=13
instruments[106]=13
instruments[107]=13
instruments[108]=13
instruments[109]=13
instruments[110]=13
instruments[111]=7
instruments[112]=13
instruments[113]=1
instruments[114]=1
instruments[115]=1
instruments[116]=1
instruments[117]=1
instruments[118]=1
instruments[119]=1
instruments[120]=1
instruments[121]=9
instruments[122]=9
instruments[123]=9
instruments[124]=9
instruments[125]=9
instruments[126]=9
instruments[127]=9

songNames = dict()

with open(os.path.join(pth, "MIDI\\songLabel.txt"), "r") as fp:
    for name in fp.readlines():
        songNames[name[:-3]] = int(name[-2]) 

#print(len(songNames), "no time" in songNames)


In [6]:
# traverse clean_midi
# function to load midi format in np array
maxgroupsz = 0
maxpad = 32112 
allMIDI, labelMIDI = [], []
def processMIDI(src, name):
    try:
        fp = MidiFile(src)
        data = [ [0]*maxpad for i in range(20) ] 
        appendat = [0 for i in range(20)]
        current_group = 0

        for i, track in enumerate(fp.tracks):
            for msg in track:
                if msg.type=='program_change':
                    current_group = instruments[msg.program]
                if msg.type=='note_on':
                    data[current_group][ appendat[current_group] ]=msg.note
                    appendat[current_group] += 1
                    

        for y in range(20):
            global maxgroupsz
            maxgroupsz = max( maxgroupsz, len(data[y]))
        allMIDI.append( np.reshape(np.asarray(data), 20*maxpad) )
        labelMIDI.append(songNames[name])
    except:
        print(src)
    
    #print(np.asarray(data))
pth1 = 'D:\\study\\major project\\scl\\clean_midi'
cnt =0
for folder in os.listdir(pth1):
    for file in os.listdir(os.path.join(pth1, folder)):
        name = file[:-4].lower()
        if name in songNames:    
            processMIDI(pth1+"\\"+folder+"\\"+file, name)
            print(cnt, name)
            cnt+=1

print(maxgroupsz)

0 dreadlock holiday
1 i'm not in love
2 simon says
3 dreams
4 never alone
5 let the beat control your body
6 maximum overdrive
7 no limit
8 no one
9 the real thing
10 tribal dance (edit)
11 twilight zone
12 workaholic
13 all mixed up
14 i need you
15 what's up
16 andra tutto bene ('58)
17 chiuditi nel cesso
18 con un deca
19 gli anni ('96)
20 grazie mille
21 hanno ucciso l'uomo ragno
22 io ci saro'
23 nella notte
24 nessun rimpianto
25 non mi arrendo
26 nord sud ovest est
27 se tornerai
28 sei un mito
29 senza averti qui
30 tieni il tempo
31 un giorno cosi
32 una canzone d'amore
33 she's out of my life
34 take on me
35 the living daylights
D:\study\major project\scl\clean_midi\Aaron Neville\Tell It Like It Is.mid
36 tell it like it is
37 chiquitita
38 dance (while the music still goes on)
39 dancing queen
40 does your mother know
41 fernando
42 gimme! gimme! gimme!
43 hey, hey helen
44 honey honey
45 i do, i do, i do, i do
46 i have a dream
47 i'm a marionette
48 kisses of fire
49 know

388 ninna nanna
389 non sono una signora
390 key largo
391 from a distance
392 the rose
393 the wind beneath my wings
394 wind beneath my wings
395 alessandra
396 iris
397 mi fai stare bene
398 non parli mai
399 se io, se lei
400 sei
401 baby i love your way
402 to be with you
403 fond memories
404 stranger on the shore
405 (we're gonna) rock around the clock
406 (we're gonna) rock around the clock
407 (i've had) the time of my life
408 ain't no sunshine
409 lean on me
410 lovely day
411 mony mony
412 rebel yell
413 white wedding
414 a matter of trust
415 allentown
416 big shot
417 don't ask me why
418 honesty
419 it's still rock and roll to me
420 just the way you are
421 leningrad
422 lullabye (goodnight, my angel)
423 my life
424 new york state of mind
425 piano man
426 prelude   angry young man
D:\study\major project\scl\clean_midi\Billy Joel\Pressure.mid
427 pressure
428 root beer rag
429 she's got a way
430 stiletto
431 tell her about it
432 the entertainer
433 the longest time
4

755 i feel for you
756 i'm every woman
757 this is my night
758 how about us
759 tequila
760 would i lie to you
761 the most beautiful girl
762 don't be cruel
763 dream police
764 the flame
765 let's twist again
766 the twist (yo twist)
767 believe
768 if i could turn back time
769 shoop shoop song
770 strong enough
771 good times
772 le freak
773 25 or 6 to 4
774 after the love has gone (live, 2004)
775 beginnings
776 colour my world
777 does anybody really know what time it is_
778 flight 602
779 hard to say i'm sorry   get away
780 hard to say i'm sorry
781 if you leave me now
782 make me smile
783 no tell lover
784 saturday in the park
785 sweet home chicago
786 spain
787 sundance (chick corea)
788 wild thing
789 pretty belinda
790 yesterday man
791 lady in red
792 missing you
793 wicked game
794 let's dance
795 auf immer und ewig
796 curse of the traveller
797 fool (if you think it's over)
798 it's all gone
799 josephine
800 julia
801 let's dance
802 little blonde plaits
803 lovin

1143 crocodile rock
1144 daniel
1145 don't go breaking my heart
1146 goodby yellow brick road
1147 i don't wanna go on with you like that
1148 i guess that's why they call it the blues
1149 i'm still standing
1150 island girl
D:\study\major project\scl\clean_midi\Elton John\Nikita.mid
1151 nikita
1152 rocket man
1153 sacrifice
1154 sad songs (say so much)
1155 song for guy
1156 the one
1157 your song
1158 fooled around and fell in love
1159 don't be cruel
1160 in the ghetto
1161 suspicious minds
1162 green shirt
1163 (let me be your) teddy bear
1164 all shook up
1165 always on my mind
1166 are you lonesome tonight
1167 blue christmas
1168 blue suede shoes
1169 burning love
1170 can't help falling in love
1171 don't be cruel
1172 fever
1173 good luck charm
1174 hard headed woman
1175 heartbreak hotel
1176 hound dog
1177 i just can't help believing
1178 in the ghetto
1179 it's now or never
1180 jailhouse rock
1181 kiss me quick
1182 let me be there
1183 love me tender
1184 my way
1185 re

1520 walking contradiction
1521 warning
1522 welcome to paradise
1523 when i come around
1524 spirit in the sky
1525 american woman
1526 no sugar tonight
1527 no time
1528 these eyes
1529 civil war
1530 don't cry
1531 dust n' bones
1532 knockin' on heaven door
1533 live & let die
1534 november rain
1535 paradise city
1536 patience
1537 sweet child o' mine
1538 welcome to the jungle
1539 you could be mine
1540 fly away
1541 life
1542 what is love
1543 (we're gonna) rock around the clock
1544 see you later alligator
1545 shake, rattle and roll
1546 everytime you go away
1547 i can't go for that (no can do)
1548 kiss on my list
1549 maneater
1550 out of touch
1551 satin doll
1552 man from milwaukee (garage mix)
1553 thinking of you
1554 axel f
1555 if you don't know me by now
1556 moviestar
1557 cat's in the cradle
1558 without you
1559 crazy for you
1560 do the limbo dance
1561 alone
1562 barracuda
1563 crazy on you
1564 these dreams
1565 boogie nights
1566 the groove line
1567 i am woma

1875 sunshine reggae
1876 an der donau steht marika
1877 auf dem leiterwagen
1878 die rose vom worthersee
1879 frisch vom fass
1880 liechtensteiner polka
1881 polka polka
1882 rosamunde
1883 schwarze amsel
1884 selfcontrol
1885 the power of love
1886 in assenza di te
1887 stanotte stai con me
1888 un'emergenza d'amore
1889 io amo
1890 io camminero
1891 mi manchi
1892 se qualcuno cercasse di te
1893 how do i live
1894 unchained melody
1895 black dog
1896 black mountain side
1897 boogie with stu
1898 bring it on home
1899 bron-y-aur stomp
1900 dazed and confused
1901 going to california
1902 good times bad times
1903 how many more times
1904 immigrant song
1905 kashmir
1906 livin' lovin' maid
1907 living loving maid (she's just a woman)
1908 misty mountain hop
1909 moby dick
1910 no quarter
1911 over the hills and far away
1912 ramble on
1913 rock and roll
1914 since i've been loving you
D:\study\major project\scl\clean_midi\Led Zeppelin\Stairway To Heaven.mid
1915 stairway to heaven
191

2234 american patrol
2235 chattanooga choo choo
2236 in the mood
2237 moonlight serenade
2238 baby don't forget my number
2239 acqua e sale
2240 amor mio
2241 brivido felino
2242 chiedimi tutto
2243 e se domani
2244 grande grande grande
2245 insieme
2246 joana francesa
2247 l'importante e finire
2248 non credere
2249 non gioco piu
2250 parole parole
2251 rose su rose
2252 the captain of her heart - every breath you take
2253 torno venerdi
2254 una zebra a pois
2255 volami nel cuore
2256 eins zwei polizei
2257 alone
2258 god moving over the face of the waters
2259 moby dick
2260 eres tu
2261 you can win if you want
2262 always look on the bright side of life
2263 andavo a cento all'ora
2264 banane e lamponi
2265 c'era un ragazzo che come me amava i beatles e i rolling stones
2266 c'era un ragazzo
2267 dove va a finire il mio affetto
2268 in ginocchio da te
2269 occhi di ragazza
2270 l'uomo dell'armonica
2271 feelings
2272 egerland heimatland
2273 only the lonely
2274 girls girls girls
2

2572 giorni infiniti
2573 giulia si sposa
D:\study\major project\scl\clean_midi\Pooh\Il cielo e blu sopra le nuvole.mid
2574 il cielo e blu sopra le nuvole
2575 il giorno prima
2576 il silenzio della colomba
2577 in diretta nel vento
2578 in silenzio
2579 io e te per altri giorni
2580 io sono vivo
2581 io ti aspettero
2582 l'altra donna
2583 la mia faccia
2584 le canzoni di domani
2585 lettera da berlino est
2586 maria marea
2587 mary ann
2588 mi manchi
2589 ninna nanna
2590 noi due nel mondo e nell'anima
2591 non dimenticarti di me
2592 non lasciarmi mai piu
2593 non siamo in pericolo
2594 parsifal (parte ii)
2595 parsifal
2596 pensiero
2597 piccola katy
2598 pierre
2599 puoi sentirmi ancora (parte 1)
2600 quaderno di donna
2601 quel che non si dice
2602 se balla da sola
2603 se sai, se puoi, se vuoi
2604 siamo ancora sulla strada
2605 sogno a mezza estate
2606 solo cari ricordi
2607 tanta voglia di lei
2608 terry b
2609 tu dov'eri
2610 un grande amore
2611 uomini soli
2612 i get a ki

2933 hold on (i'm coming)
2934 soul man
2935 stop
2936 (what a) wonderful world
2937 those were the days
2938 don't let me be misunderstood
2939 black magic woman   gypsy queen
2940 evil ways
2941 maria maria
2942 oye como va
2943 samba pa ti
2944 she's not there
2945 smooth
2946 adia
2947 affirmation
2948 truly madly deeply
2949 come on eileen
2950 the boys and me
2951 major tom
2952 endless summer
2953 greensleeves
2954 hello josephine
2955 send me an angel
2956 wind of change
2957 you and i
2958 grace and beauty
2959 great scott rag
2960 paragon rag
2961 the entertainer
2962 forrest gump_ san francisco (be sure to wear some flowers in your hair)
2963 crazy
2964 fly like an eagle
2965 kiss from a rose
2966 summer breeze
2967 needles and pins
2968 oh carol
2969 sunny
2970 angel
2971 boombastic
2972 it wasn't me
2973 easier said than done
2974 night birds
2975 from this moment on
2976 i love your smile
2977 da doo ron ron
2978 if i should lose you
2979 the wind beneath my wings
2980 u 

3289 free as a bird
3290 from me to you
3291 get back
3292 getting better
3293 glad all over
3294 glass onion
3295 golden slumbers
3296 good day sunshine
3297 good morning good morning
3298 good night
3299 got to get you into my life
3300 happiness is a warm gun
3301 hark the herald angels sing (help)
3302 hello goodbye
3303 help!
3304 helter skelter
3305 her majesty
3306 here comes the sun
3307 here, there and everywhere
3308 hey bulldog
3309 hey jude
3310 honey don't
3311 honey pie
3312 how do you do it
3313 i am the walrus
3314 i call your name
3315 i feel fine
3316 i me mine
3317 i need you
3318 i saw her standing there
3319 i should have known better
3320 i wanna be your man
3321 i want to hold your hand
3322 i want you (she's so heavy)
3323 i will
3324 i'll be back
3325 i'll cry instead
3326 i'll follow the sun
3327 i'll get you
3328 i'm a loser
3329 i'm down
3330 i'm happy just to dance with you
3331 i'm so tired
3332 i've got a feeling
3333 i've just seen a face
3334 if i fell


3652 unchained melody
3653 walk don't run
3654 wonderful land
3655 1979
3656 disarm
3657 landslide
3658 thirty-three
3659 today
3660 tonight, tonight
3661 zero
3662 gimme some lovin'
3663 keep on running
3664 amapola
3665 happy guitar
3666 dirty water
3667 golden brown
3668 shout to the top
3669 you are everything
3670 you make me feel brand new
3671 baby love
3672 wipe out
3673 ain't too proud to beg
3674 ball of confusion (that's what the world is today)
3675 get ready
3676 i can't get next to you
3677 just my imagination
3678 my girl
3679 papa was a rolling stone
3680 disco inferno
3681 my little lady
3682 silence is golden
3683 love is all around
3684 wild thing
3685 apache
3686 besame mucho
3687 i feel fine
3688 pipeline
3689 walk don't run
3690 the freshman
3691 one headlight
3692 it's raining men
3693 my generation
3694 pinball wizard
3695 substitute
3696 summertime blues
3697 these eyes
3698 for you love
3699 don't leave me this way
3700 gloria
3701 zorba's dance
3702 whiskey i

In [7]:
print(allMIDI[0])
print(labelMIDI[0])
print(len(allMIDI))
print(len(labelMIDI))
print('done')

[37 37 37 ...  0  0  0]
0
3922
3922
done


In [8]:
#print(temp1.shape[0])
#no,yes
temp_y=[]
for l in labelMIDI:
    p=[]
    if l==1:
        p=[0,1]
    else:
        p=[1,0]
    temp_y.append(p)
#print(temp_y)    
Y=temp_y
print(Y[0])

[1, 0]


In [9]:
#total 3922 70%:30% 
X_test=[]
X_train=[]
Y_train=[]
Y_test=[]
i=0
for label in Y:
    if i<2750:
        Y_train.append(label)
    else:
        Y_test.append(label)
    i+=1
i=0
for row in allMIDI:
    if i<2750:
        X_train.append(row)
    else:
        X_test.append(row)
    i+=1   
print(len(X_train))
print(len(X_test))
print(len(Y_train))
print(len(Y_test))
print(Y_train[0])
print(Y_test[0])
allMIDI=None
labelMIDI=None

2750
1172
2750
1172
[1, 0]
[0, 1]


In [10]:
batch_size = 128
num_classes = 2
epochs = 5

# input image dimensions

img_x, img_y = 20,maxpad


In [11]:
#list to numpy array conversion
x_train=np.asarray(X_train)
x_test=np.asarray(X_test)
y_train=np.asarray(Y_train)
y_test=np.asarray(Y_test)
x_train = x_train.reshape(x_train.shape[0], img_y, img_x,1)
x_test = x_test.reshape(x_test.shape[0], img_y, img_x,1)
input_shape = (img_y, img_x,1)

In [12]:
print(x_train.shape)
print(y_train)
print('done')

(2750, 32112, 20, 1)
[[1 0]
 [1 0]
 [0 1]
 ...
 [1 0]
 [1 0]
 [1 0]]
done


In [13]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(25, 5), strides=(3,3),
                 activation='relu',
                 padding='same',
                 input_shape=input_shape,
                data_format='channels_last'))

print(model.output_shape)
model.add(MaxPooling2D(pool_size=(2,2),strides=(2,2)))
print(model.output_shape)
model.add(Conv2D(64, kernel_size=(10, 3), strides=(1, 3),

                  activation='relu',
                  padding='same',
                  input_shape=input_shape,
                 data_format='channels_last'))

print(model.output_shape)
model.add(MaxPooling2D(pool_size=(2,1),strides=(2,1)))
print(model.output_shape)
model.add(Flatten())
print(model.output_shape)
#model.add(Dropout(0.2))
#model.add(Dense(1024, actxivation='relu'))
model.add(Dense(1024, activation='relu'))
print(model.output_shape)
model.add(Dense(num_classes, activation='softmax'))
print(model.output_shape)
model.compile(loss=keras.losses.categorical_crossentropy,

              optimizer=keras.optimizers.Adam(),

              metrics=['accuracy'])





class AccuracyHistory(keras.callbacks.Callback):

    def on_train_begin(self, logs={}):

        self.acc = []



    def on_epoch_end(self, batch, logs={}):

        self.acc.append(logs.get('acc'))



history = AccuracyHistory()



model.fit(x_train, y_train,

          batch_size=batch_size,

          epochs=epochs,

          verbose=1,

          validation_data=(x_test, y_test),

          callbacks=[history])

score = model.evaluate(x_test, y_test, verbose=0)

print('Test loss:', score[0])

print('Test accuracy:', score[1])

'''plt.plot(range(1, 11), history.acc)

plt.xlabel('Epochs')

plt.ylabel('Accuracy')

plt.show()    
'''



(None, 10704, 7, 32)
(None, 5352, 3, 32)
(None, 5352, 1, 64)
(None, 2676, 1, 64)
(None, 171264)
(None, 1024)
(None, 2)
Train on 2750 samples, validate on 1172 samples
Epoch 1/5
2750/2750 [==============================] - 592s 215ms/step - loss: 5.1340 - acc: 0.6549 - val_loss: 5.6524 - val_acc: 0.6493
Epoch 2/5
2750/2750 [==============================] - 588s 214ms/step - loss: 5.2867 - acc: 0.6720 - val_loss: 5.6523 - val_acc: 0.6493
Epoch 3/5
2750/2750 [==============================] - 588s 214ms/step - loss: 5.2867 - acc: 0.6720 - val_loss: 5.6523 - val_acc: 0.6493
Epoch 4/5
2750/2750 [==============================] - 581s 211ms/step - loss: 5.2867 - acc: 0.6720 - val_loss: 5.6523 - val_acc: 0.6493
Epoch 5/5
2750/2750 [==============================] - 580s 211ms/step - loss: 5.2867 - acc: 0.6720 - val_loss: 5.6523 - val_acc: 0.6493
Test loss: 5.652335548563622
Test accuracy: 0.6493174065502023


"plt.plot(range(1, 11), history.acc)\n\nplt.xlabel('Epochs')\n\nplt.ylabel('Accuracy')\n\nplt.show()    \n"

In [72]:
# loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
# maxpad=32112
# Q=[]
# def processComingMIDI(src):
#     try:
#         fp = MidiFile(src)
#         data = [ [0]*maxpad for i in range(20) ] 
#         appendat = [0 for i in range(20)]
#         current_group = 0

#         for i, track in enumerate(fp.tracks):
#             for msg in track:
#                 if msg.type=='program_change':
#                     current_group = instruments[msg.program]
#                 if msg.type=='note_on':
#                     data[current_group][ appendat[current_group] ]=msg.note
#                     appendat[current_group] += 1
                    

# #         for y in range(20):
# #             global maxgroupsz
# #             maxgroupsz = max( maxgroupsz, len(data[y]))
#         global Q
#         Q= [np.reshape(np.asarray(data), 20*maxpad) ]
#         #labelMIDI.append(songNames[name])
#     except:
#         print(src)
# #print(Q,"^^")    
# processComingMIDI("D:\study\major project\scl\clean_midi\ABBA\Super Trooper.mid") 
# Q=np.asarray(Q)
# Q = Q.reshape(Q.shape[0], img_y, img_x,1)
# print(Q,"**")
# # evaluate loaded model on test data
# score = model.predict(Q)
# print(score,"@@@@@@")

[[[[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  ...

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]

  [[0]
   [0]
   [0]
   ...
   [0]
   [0]
   [0]]]] **
[[0. 1.]] @@@@@@


In [80]:

#save the model
#serialize model to json
model_json = model.to_json()
print(os.getcwd())
#os.chdir(os.path.join(os.getcwd(),"MIDI"))
with open("model.json", "w") as json_file:
    json_file.write(model_json)
    print("hello")

# serialize weights to HDF5

model.save_weights("model.h5")
print("Saved model to disk")


D:\study\major project\scl\src\MIDI
hello
Saved model to disk


In [41]:
# model_json = model.to_json()
# with open("model.json", "w") as json_file:
#     json_file.write(model_json)
# # serialize weights to HDF5
# model.save_weights("model.h5")
# print("Saved model to disk")

Saved model to disk


In [81]:
# load json and create model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")

Loaded model from disk


In [86]:
loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
maxpad=32112
Q=[]
def processComingMIDI(src):
    try:
        fp = MidiFile(src)
        data = [ [0]*maxpad for i in range(20) ] 
        appendat = [0 for i in range(20)]
        current_group = 0

        for i, track in enumerate(fp.tracks):
            for msg in track:
                if msg.type=='program_change':
                    current_group = instruments[msg.program]
                if msg.type=='note_on':
                    data[current_group][ appendat[current_group] ]=msg.note
                    appendat[current_group] += 1
                    

#         for y in range(20):
#             global maxgroupsz
#             maxgroupsz = max( maxgroupsz, len(data[y]))
        global Q
        Q= [np.reshape(np.asarray(data), 20*maxpad) ]
        #labelMIDI.append(songNames[name])
    except:
        print(src)
#print(Q,"^^")    
processComingMIDI("D:\study\major project\scl\clean_midi\Pink Floyd\Have a Cigar.mid") 
Q=np.asarray(Q)
Q = Q.reshape(Q.shape[0], img_y, img_x,1)
#print(Q,"**")
# evaluate loaded model on test data
score = loaded_model.predict(Q)
print(score,"@@@@@@")

[[1. 0.]] @@@@@@


In [88]:
loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
maxpad=32112
Q=[]
def processComingMIDI(src):
    try:
        fp = MidiFile(src)
        data = [ [0]*maxpad for i in range(20) ] 
        appendat = [0 for i in range(20)]
        current_group = 0

        for i, track in enumerate(fp.tracks):
            for msg in track:
                if msg.type=='program_change':
                    current_group = instruments[msg.program]
                if msg.type=='note_on':
                    data[current_group][ appendat[current_group] ]=msg.note
                    appendat[current_group] += 1
                    

#         for y in range(20):
#             global maxgroupsz
#             maxgroupsz = max( maxgroupsz, len(data[y]))
        global Q
        Q= [np.reshape(np.asarray(data), 20*maxpad) ]
        #labelMIDI.append(songNames[name])
    except:
        print(src)
#print(Q,"^^")        
pth1 = 'D:\\study\\major project\\scl\\clean_midi'
cnt=0;
#pth1 = 'D:\\study\\major project\\scl\\clean_midi\\AC DC'        
for folder in os.listdir(pth1):
    for file in os.listdir(os.path.join(pth1, folder)):
        name = file[:-4].lower()
        if name in songNames:    
            processComingMIDI(pth1+"\\"+folder+"\\"+file)
            #print(cnt, name)
            cnt+=1       
            #processComingMIDI("D:\study\major project\scl\clean_midi\AC DC\Highway To Hell.mid") 
            Q=np.asarray(Q)
            Q = Q.reshape(Q.shape[0], img_y, img_x,1)
            #print(Q,"**")
            # evaluate loaded model on test data
            score = loaded_model.predict(Q)
            #print(score,"@@@@@@")
            #print(score,name)
            if score[0][0]==0 and score[0][1]==1:
                print(name)
        if cnt==1000:
            break;

        print("knock")  
    if cnt==1000:
        break

knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
D:\study\major project\scl\clean_midi\Aaron Neville\Tell It Like It Is.mid
knock
knock
knock
knock
knock
knock
knock
knock
k

knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knoc

knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
the old playground
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
kno

knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
D:\study\major project\scl\clean_midi\Creedence Clearwater Revival\Suzie Q.mid
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
knock
kno